AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Content Creator's Co-Pilot: An autonomous AI agent for content creation.

Parameters:
  TavilyAPIKeyParameterName:
    Type: String
    Description: The name of the SSM Parameter Store parameter holding the Tavily API key.
    Default: /content-creator-copilot/tavily-api-key
  
  S3BucketName:
    Type: String
    Description: The name of the existing S3 bucket for storing agent data.
    Default: aws-hackathon-content-creator-copilot-data

Globals:
  Function:
    Timeout: 600 
    MemorySize: 512 
    Runtime: python3.12
    Architectures: [arm64]
    Environment:
      Variables:
        S3_BUCKET_NAME: !Ref S3BucketName
    
Resources: 

  ResearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: research-tool
      CodeUri: src/tools/research/
      Handler: app.lambda_handler
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          TAVILY_API_KEY_PARAM_NAME: !Ref TavilyAPIKeyParameterName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName 
        - Statement:
            - Effect: Allow
              Action: [ssm:GetParameter]
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${TavilyAPIKeyParameterName}"

  IdeationFunction:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: ideation-tool
        CodeUri: src/tools/ideation/
        Handler: app.lambda_handler
        Policies:
          - S3CrudPolicy:
              BucketName: !Ref S3BucketName
          - Statement:
              - Effect: Allow
                Action: [bedrock:InvokeModel]
                Resource: '*'

  ScriptwritingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: scriptwriting-tool
      CodeUri: src/tools/scriptwriting/
      Handler: app.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - Statement:
            - Effect: Allow
              Action: [bedrock:InvokeModel]
              Resource: '*'

  SocialMediaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: social-media-tool
      CodeUri: src/tools/social_media/
      Handler: app.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - Statement:
            - Effect: Allow
              Action: [bedrock:InvokeModel]
              Resource: '*'
  
  FileSaverFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: file-saver-tool
      CodeUri: src/tools/file_saver/
      Handler: app.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName

  AgentApiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: agent-api-handler
      CodeUri: src/api_handler/
      Handler: app.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action: [bedrock:InvokeAgent]
              Resource: "arn:aws:bedrock:us-east-1:393182762897:agent/NKPXB6ZA0W"
      Environment:
        Variables:
          BEDROCK_AGENT_ID: "NKPXB6ZA0W"
          BEDROCK_AGENT_ALIAS_ID: "TSTALIASID" # Use the draft alias
      Events:
        AgentApi:
          Type: Api
          Properties:
            Path: /invoke
            Method: post

  FrontendWebApp:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:390328229243:applications/apprunner-streamlit
        SemanticVersion: 1.0.1
      Parameters:
        EnvironmentVariables: !Sub "BEDROCK_AGENT_API_URL=https://$\{ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/invoke"




  